### ISSUE TITLE
Wrong file locations and names

### ISSUE THREAD

**Issue by tyhoff** [alexharris/calm-shallow-sea#1]
When I applied the theme to a vanilla Octopress installation, the front page had two errors in plain text.
1. Included file 'custom/head.html' not found in _includes directory
2. Included file 'disqus.html' not found in _includes directory

The disqus.html file was in the source directory at `calm-shallow-sea/source/disqus.html`. 

Also, the stylesheet style.css refers to a folder at location `../img/`. This folder is actually named `/images/` in the repo, so I'd suggest changing one or the other.

**Comment by alexharris** [comment]
Hi,

I just pushed some changes that should fix the issues that you pointed out. Would you mind trying to install the new version and see if the problems are addressed? Thanks for pointing them out.

Alex

**Comment by alexharris** [comment]
Thanks for pull request, I have merged it.

I guess I am unsure as to whether it is more correct to remove the call to an unused "custom" include, or just create the include but have it be blank, as you have done. I suppose it is octopress convention to have the custom includes even if they are not used, but I would generally rather just remove the call to it. It seems more simple.

Also, I believe you can name your commit in such a way that it automatically closes the related issue. See here: https://github.com/blog/1386-closing-issues-via-commit-messages

thanks again,
Alex
