### ISSUE TITLE
Compatible GitHub Flavored Markdown

### ISSUE THREAD

**Issue by zono** [alexharris/calm-shallow-sea#3]
Hi, I really love this theme. However, this theme seems not be compatible GitHub Flavored Markdown. Some mark down does not work like Lists, Blockquotes and so on. I would really grateful if you prepare Markdown Cheatsheet. I am trying to fix it by myself.. but not easy for me.

**Comment by alexharris** [comment]
Hello,

I am not familiar with GitHub Flavored Markdown...can you tell me more specifically what issues you are having?

If I am not mistaken, the type of markdown that you use is something that needs to be configured in your instance of Jekyll, something along the lines of: http://yangsu.github.io/blog/2012/10/11/using-octopress-with-github-flavored-markdown-redcarpet/. As far as I know, the theme you are using should have nothing to do with this.

Are you able to use GFM with other themes you have tried?

thanks,
Alex

**Comment by zono** [comment]
Hello

Thanks for your reply. Yes, I have tried to use GFM with other themes like below.

(e.g. BLOCKQUOTE)

When I write this markdown..

```
> The problem on iOS devices is that Apple's CoreBluetooth APIs disallow access to the raw advertisement body, so no third-party app is able to read these identifiers
```

I expecte like this below

> The problem on iOS devices is that Apple's CoreBluetooth APIs disallow access to the raw advertisement body, so no third-party app is able to read these identifiers

The following themes work normally.
- Default theme (classic)
- https://github.com/amelandri/darkstripes
- https://github.com/rezajatnika/greyjoy

I try to fix it by myself!! 

Thanks,
Zono

**Comment by alexharris** [comment]
Hi, ok let me know if you can't get it resolved and I can take a look at it. Also, if you do figure it out, feel free to post the solution here!

thanks,
Alex
